name: Upload web components to WP Hosting

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies and build
        run: |
          npm install
          npm run build --if-present
      - name: Upload with SFTP
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: ${{ secrets.SFTP_HOST }}
          port: 22
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          privateKey: ${{ secrets.SFTP_PRIVATE_KEY }}
          localPath: ./public
          remotePath: ./wp-newsite/wp-content/plugins/miles-wp-web-components-plugin/miles-wc-new
